### ISSUE TITLE
Request to expose audi_services.set_battery_charger to Home Assistant

### ISSUE THREAD

**Issue by duckend** [arjenvrh/audi_connect_ha#19]
I noticed there is the code for set_battery_charger in audi_services.py that wasn't exposed as an action to Home Assistant. Being able to control when our car charges is a big win over the simple scheduling offered by Audi and opens the possibility of charging...

- when time of use electricity rates are low
- outside grid peak demand periods
- when local solar production has excess

The good news is that I can confirm the api call to both start and stop charging works on our A3 Etron after coding up start_charging / stop_charging actions using start_climatisation as a template. is this something you are planning to add in a future update, or would you be agreeable for me to issue a Pull request with my changes. 

Regards,
Iain

**Comment by tnagels** [comment]
Arjen did some tests on my e-Tron over the weekend so this may be coming.

But for your information: it is possible to get your car to charge on low rate periods (with my e-Tron at least). You cannot do this form the app, but in the car there are extended charge settings where you can define locations and set preferred charging times.

For example, I have set this for my home to prefer charging between 22:00 and 07:00. Now when I set a timer for 08:00 the car will actually be ready at 07:00 because it knows rates are cheaper then.

That said, charge control from HA would be great!


Thomas

**Comment by duckend** [comment]
Thanks Thomas,

As Arjen is working on it I'll leave it as is.

Unfortunately the in car scheduling doesn't work for our scenario, where we are attempting to start charging when returning home in the afternoon but not allow the car to charge between 16:00 & 19:00. The car would start charging at 15:00 when plugged in, but continue charging until fully charged instead of stopping once the peak period was reached.

Happily, using Home Assistant, we can now control when the car can and can't charge and now pause charging at 16:00 to later resume at 19:00.

Iain

**Comment by arjenvrh** [comment]
Hi Iain

Just updated the code where a charging option is included in the service call, it should work but let me know if it doesn't.

Regards
Arjen

**Comment by duckend** [comment]
Thanks Arjen,

I'll update tomorrow when I'm at home.

Iain

**Comment by duckend** [comment]
Updated and charge control working well.

Thanks for your work
Iain
