### ISSUE TITLE
Setup failed for beautifulsoup4: Integration not found.

### ISSUE THREAD

**Issue by mitch-dc** [arjenvrh/audi_connect_ha#42]
After updating, i get this error:

`Setup failed for beautifulsoup4: Integration not found.`

**Comment by guerrerotook** [comment]
{
  "domain": "audiconnect",
  "name": "Audi Connect",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/components/audiconnect",
  "requirements": [],
  "dependencies": ["beautifulsoup4"],
  "codeowners": ["@arjenvrh"]
}

Instead of using the requeriments property you used the dependencies.

**Comment by pergolafabio** [comment]
i changed indeed, now it works

**Comment by arjenvrh** [comment]
Corrected, must have been sleeping
